### ISSUE TITLE
Some image formats (SVG, JPG) don't work on the portal

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#16]

**Comment by Pikkuninja** [comment]
I've noticed this with svg images, pngs work fine.

**Comment by antti-TIEA4** [comment]
It also doesn't seem to work with background images added via CSS. (Though that is just a temporary thing in this app, so it really doesn't matter)

**Comment by antti-TIEA4** [comment]
I've seen other projects use the [$mdIconProvider](https://material.angularjs.org/latest/api/service/$mdIconProvider) service for icons. Perhaps that should be tested.

**Comment by antti-TIEA4** [comment]
Reported here: https://github.com/llb-uta/development-kit/issues/3
