### ISSUE TITLE
Create basic UI for tile and fullscreen

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#3]

**Comment by Pikkuninja** [comment]
+1 for directives. For example if the markup for each event on the list was just written in some ng-repeat, and then you'd want to keep displaying the clicked event while showing the map you'd be screwed.

**Comment by antti-TIEA4** [comment]
@Pikkuninja 
Not sure if I evaded the pitfall you described. I initially made my own directives, then realized that we should use the material UI directives and used them. I guess it's still possible to wrap them in some custom directive if needed.
