### ISSUE TITLE
Display exact distance on each card

### ISSUE THREAD

**Issue by Mxdcq** [APT-project/upcoming#43]

**Comment by antti-TIEA4** [comment]
This sounds like a job for those Angular output filters.
There's already a builtin filter for [currency](https://docs.angularjs.org/api/ng/filter/currency) but looks like we have to create (read: Google) a filter for distances.

**Comment by Mxdcq** [comment]
I am moving on to work on it.

**Comment by antti-TIEA4** [comment]
Sweet, I'll assign you to it. (You can do this from the panel on the right calles **Assignees**)

**Comment by Mxdcq** [comment]
```
<span class="event-title">
            <span>{{ event.name }}</span>
            <span ng-if="event.venue">@{{ event.venue }}</span>
          </span>
```
How about add {{event.distanceToUser}} here. Because we add a new attribute to event.
```
events[i].distanceToUser =
          getDistanceFromLatLonInKm(Number(events[i].latitude),
                                    Number(events[i].longitude),
                                    Number(coordinates.latitude),
                                    Number(coordinates.longitude));
```

**Comment by antti-TIEA4** [comment]
Yeah, it should go somewhere in that `md-card` element.

By the way, those `md-card`s have all kinds of ready made style elements if you want to make them look prettier. See: https://material.angularjs.org/latest/demo/card
(If you press the `< >` button in the toolbar on that page, you will see the source code of the demos)

**Comment by Mxdcq** [comment]
I will try if I finish displaying the distance of on the card.
