### ISSUE TITLE
No distance display after refresh 

### ISSUE THREAD

**Issue by Mxdcq** [APT-project/upcoming#44]
Everything works well if I launch the sever from command line. After click into a typical event and then refresh the page. The distance will disappear. I have to click the 'back' button and click into the event again, the distance will display. Maybe we need something to trigger off the proximity function.

**Comment by antti-TIEA4** [comment]
I cannot reproduce this? I'm using Chrome.

**Comment by Mxdcq** [comment]
I use Chrome too.

**Comment by antti-TIEA4** [comment]
Have you granted the location permission?

**Comment by Mxdcq** [comment]
Of course, I grant. I have no idea why.

**Comment by Pikkuninja** [comment]
For what I tested, on chrome I get the same bug as @Mxdcq. On firefox the distance doesn't ever show up.

**Comment by antti-TIEA4** [comment]
Are we all using the latest version 91f0257967d0a730481c485358fe253d4c24ad57?
Just noticed that @Mxdcq reported this 6 hours ago when the thing didn't work at all

**Comment by Pikkuninja** [comment]
I downloaded the master branch as zip 15mins ago and tested on that.

**Comment by antti-TIEA4** [comment]
Here's how I understood the original report:

1. Start the live server
1. Click the tiles
1. I see distances on the event list
1. I click the first event
1. Map shows up
1. I "refresh the page" (F5)
1. I see the tile mode again and click it
1. Event list shows up and the distances are there

**Comment by Mxdcq** [comment]
@Pikkuninja I think we should use Chrome at this stage. Because on safari, nothing shows up after choosing the device and size.

**Comment by Pikkuninja** [comment]
7. I see the tile mode again and click it

Did you do some voodoo magic to your devkit? The current devkit should keep the app in fullscreen between refreshes.

**Comment by antti-TIEA4** [comment]
No idea :D
But I can reproduce this now if I F5 directly on the sidenav event list.

I guess the refresh loads the EventController again, which fetches the original `mock.events.json` and then the location does not get updated and the distances are not updated.

**Comment by Pikkuninja** [comment]
Had to fire up my old macbook to check the Safari issue. For me the devkit doesn't even allow me to select the tile size, and all the apps on the actual portal work in tile mode but show a white screen in fullscreen.

...

Cool
