### ISSUE TITLE
Event list is broken

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#48]

**Comment by Mxdcq** [comment]
Haha. You live in city center I think.

**Comment by antti-TIEA4** [comment]
Yeah, I live under the Hämeensilta bridge :)
Good wifi, nice view.

**Comment by Mxdcq** [comment]
<img width="762" alt="screen shot 2016-12-05 at 10 19 21 pm" src="https://cloud.githubusercontent.com/assets/15731144/20900949/f641bafe-bb38-11e6-9e89-fe80d14f7f96.png">
Is this looks better?

**Comment by antti-TIEA4** [comment]
Can you take a screenshot when it's scrolled all the way down?

**Comment by Mxdcq** [comment]
Oh. It seems bad.

**Comment by Mxdcq** [comment]
<img width="1440" alt="screen shot 2016-12-05 at 11 28 54 pm" src="https://cloud.githubusercontent.com/assets/15731144/20903073/a7cd9cd0-bb42-11e6-8320-4b07d3b6dee2.png">
How about add a scroll bar.

**Comment by Pikkuninja** [comment]
Nope, sounds horrible usability-wise.

Make the spacing between each type of text (title, distance, description) a bit smaller so it fits 2 lines of description text. Then find a way to cut the text and add '...' at the point that the third line would start. Then the card that appears at the bottom of the screen when you click an event can show the whole description text.

**Comment by Mxdcq** [comment]
<img width="324" alt="screen shot 2016-12-06 at 12 01 05 am" src="https://cloud.githubusercontent.com/assets/15731144/20904198/3c1f4088-bb47-11e6-9876-279d8b02cf08.png">

I set the margin-top and margin-bottom to 0 for tag `<p>`

**Comment by antti-TIEA4** [comment]
Yeah, hell no for scroll bars in cards :)

@Pikkuninja pretty much described how it should work. And that's how I tried to do it. I tried to make the content text cut off if it got out of bounds of the `md-card` but I failed. I thought [`text-overflow: ellipsis`](https://github.com/APT-project/upcoming/blob/91f0257967d0a730481c485358fe253d4c24ad57/app/css/style.css#L23) would take care of that but it doesn't work. Turns out I'm basically clueless when it comes to CSS or Angular UI components. Nothing seems to work, and if I magically get it to work, it will burn if I try to change one thing.

**Comment by antti-TIEA4** [comment]
@Mxdcq That screenshot seems to solve the immediate bug, but it doesn't look very pretty :D
Though even the original didn't look very pretty ;)
If you are good at CSS could you make the distance show/float on the top right corner of the box?

**Comment by antti-TIEA4** [comment]
I mean like this:
<img width="264" alt="3c1f4088-bb47-11e6-9876-279d8b02cf08" src="https://cloud.githubusercontent.com/assets/22329344/20905619/3f58dc2c-bb4d-11e6-80f4-3043b0aaded0.png">

**Comment by Mxdcq** [comment]
you already did it?
This is bottom right not top right.

**Comment by antti-TIEA4** [comment]
No, that's a mockup

**Comment by Pikkuninja** [comment]
@antti-TIEA4 with mad photoshop skillz

**Comment by Mxdcq** [comment]
<img width="324" alt="screen shot 2016-12-06 at 1 00 40 am" src="https://cloud.githubusercontent.com/assets/15731144/20906171/766ffc48-bb4f-11e6-9b09-7158b1973ea3.png">

Right now?

**Comment by antti-TIEA4** [comment]
Yeah, like that! Looks much cleaner now :clap:

**Comment by Mxdcq** [comment]
I did this under my master branch. Fuck!!!
