### ISSUE TITLE
Improve event list UI

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#5]

**Comment by antti-TIEA4** [comment]
Word wrapping just doesn't seem to work with `md-button`s. 
![screenshot from 2016-11-08 00-24-32](https://cloud.githubusercontent.com/assets/22329344/20078656/31fad6c0-a54a-11e6-8209-64cd12382402.png)
Was able to get the uppercasing removed with `"text-transform: none !important;"` but neither `"overflow-wrap: break-word !important;"` nor `"word-wrap: break-word !important;"` work.

[https://github.com/angular/material/issues/582](https://goo.gl/Ms0I4y)
> I don't think Material Design allows for [wrapping the text on the button], looking at the spec for buttons: http://www.google.com/design/spec/components/buttons.html
>
> Buttons have to be able to fit into different places in the UI, such as persistent footers, which have limited heights. Can you put supporting text next to the button?
