### ISSUE TITLE
Add distance to tiles

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#56]

**Comment by Mxdcq** [comment]
If we can fix issue-44, then we can add the distance on the tiles.

**Comment by Mxdcq** [comment]
![screen shot 2017-01-03 at 2 29 05 pm](https://cloud.githubusercontent.com/assets/15731144/21607770/083c2020-d1c1-11e6-965a-891db8d9d1d9.png)
Do we need to place the distance at the right bottom corner or at the center center?

**Comment by antti-TIEA4** [comment]
I think right bottom corner would look more consistent with the other list view. In any case, the distance should be somehow visually separated from the event info.

**Comment by antti-TIEA4** [comment]
Or you could use those `md-card` sub-elements. The whole cards should anyway be redone with `md-card`s

**Comment by Mxdcq** [comment]
But the third tile is the name of our App. So there is no distance feature in that tile. If we do right bottom at the first two tiles, it seems unbalance.

**Comment by Mxdcq** [comment]
That's a good suggestion.

**Comment by antti-TIEA4** [comment]
Now that you mention it I think _"Show more upcoming **stops**"_ looks weird. It would be better if it said _"Show more upcoming **events**"_ because the tiles contain events not stops.

**Comment by heinoapt** [comment]
Are "Close to me" and "Try" trimmed from events? Those could contain something meaningful about the event.

Maybe we could use an image as well on the tiles?

**Comment by Mxdcq** [comment]
Yeah. They are from mock json file. If we want to use images, I think we should add an 'image' key in each mock data.

**Comment by antti-TIEA4** [comment]
I agree that they should have more meaningful content.

The tiles should be redone with `md-card` https://material.angularjs.org/latest/demo/card
#55 is tracking that.

**Comment by heinoapt** [comment]
ok, that looks good. Let's add a tileText or similar to the mock data, that way we can make sure the text is meaningful. At the same time the image would be good too, it could have two versions as well, a thumbnail and the image itself.

**Comment by antti-TIEA4** [comment]
Currently the tiles use the event name and venue name.
The mock data looks like this
https://github.com/APT-project/upcoming/blob/64308b8f0e3e6571f71747c0bf665682672b5c51/app/data/mock.events.json

I'm not sure if `tileText` is needed? But it could make sense as a space constrained version because the event names and venues could be lengthy. (Especially when the ellipsis CSS does not seem to work :sob: )

@Mxdcq when you make a PR of this change, could you also change the last two events you added previously to contain something more meaningful?

**Comment by heinoapt** [comment]
I was thinking about the long texts too. It's not mandatory at all, the image would make a bigger improvement I think.

**Comment by Mxdcq** [comment]
I will modify them.

**Comment by Mxdcq** [comment]
I used the `md-card`, `md-button` following the link you given. If we simply use the CSS class `md-headline`, `md-subhead`, etc. The style is not suitable for us,  especially some events with long description.
![screen shot 2017-01-03 at 5 40 24 pm](https://cloud.githubusercontent.com/assets/15731144/21613251/27909dfe-d1dd-11e6-9a4f-7c7d290fbfbe.png)
![screen shot 2017-01-03 at 5 40 33 pm](https://cloud.githubusercontent.com/assets/15731144/21613250/278eb458-d1dd-11e6-9c3a-f147a302def6.png)

**Comment by antti-TIEA4** [comment]
How can the `md-card` subelements get out of the `md-card`?

**Comment by antti-TIEA4** [comment]
There seems to be a lot of margin/padding (or whatever it's called in CSS) on the top and on the left

**Comment by Mxdcq** [comment]
Yeah. The example also has a lot of margin.
<img width="413" alt="screen shot 2017-01-03 at 5 56 38 pm" src="https://cloud.githubusercontent.com/assets/15731144/21613468/03a7fc06-d1de-11e6-8207-a18136cb7827.png">

**Comment by antti-TIEA4** [comment]
We can't afford that much margin as in the example.

**Comment by antti-TIEA4** [comment]
In any case you can just add the distance the old way for now (without doing any `md-card` stuff) and then when that's done, you can move on to #55 to try to make the `md-card` work.

**Comment by Pikkuninja** [comment]
Btw while you guys are adjusting placements / space between elements, add a small margin to right of the distance text, it's kinda annoying that the 'm' in 'km' or 'm' almost connects with the card border.

**Comment by antti-TIEA4** [comment]
8638e5e69e4b284e574771848b0631ac5b51df3a
