### ISSUE TITLE
Hide sidenav by default

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#70]

**Comment by Mxdcq** [comment]
I find that in large screens, the bottom of sidenav will be empty with white space because there are only 6 events in our mock data. Is this a big problem we should solve?

**Comment by Mxdcq** [comment]
I prefer to add more events. Haha.

**Comment by Mxdcq** [comment]
There are two ways to hide the sidenav by default.
1. The simpler one is to set  `md-is-open="true"` to `md-is-open="false"`.
2. Another one is to use `md-is-locked-open="$mdMedia('gt-xs')"` ----- https://material.angularjs.org/latest/api/service/$mdMedia
When I use the second method, there is a interlaced as the picture below if we choose large size screen.
![screen shot 2017-01-05 at 2 12 22 pm](https://cloud.githubusercontent.com/assets/15731144/21680286/7c01d3f6-d351-11e6-9de0-b60cb638c076.png)

**Comment by antti-TIEA4** [comment]
Ok, I played with it now. I see what you mean. Let's just use option 1.
