### ISSUE TITLE
Emojis take too much line space

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#81]

**Comment by heinoapt** [comment]
That was a cool idea! I don't know how to resolve the linespacing thing, but maybe if the emoticon was on it's own element, it could have an absolute position above other input?

**Comment by antti-TIEA4** [comment]
Yeah, that could work. But maybe too much hassle to circumvent a clear Firefox issue?
This is causing problems on all pages on the web that have emojis. E.g. copying text is sometimes impossible if there are emojis on the page.. I bet there's a bug report about this in the mozilla tracker. After a quick search found this https://bugzilla.mozilla.org/show_bug.cgi?id=1158829

**Comment by heinoapt** [comment]
That's true. A bit too much hassle to add it with Android Firefox support.
