### ISSUE TITLE
Sort events by proximity to user

### ISSUE THREAD

**Issue by ghost** [APT-project/upcoming#9]

**Comment by antti-TIEA4** [comment]
@Mxdcq would you like to implement this?

**Comment by Mxdcq** [comment]
Okay.

**Comment by antti-TIEA4** [comment]
So it should be something like this:
```js
events = [
  {
    "id": 0,
    "name": "Bowling discount",
    "venue": "",
    "description": "",
    "latitude": "61.494413",
    "longitude": "23.762998",
    "busstops": ["1337", "8888"],
    "priority": 0
  },
  {
    "id": 1,
    "name": "Free buckets",
    "venue": "Hämeensilta",
    "description": "Buy a Tesla, get one bucket for free",
    "latitude": "61.498002",
    "longitude": "23.763586",
    "busstops": ["4311", "0800", "8135"],
    "priority": 0
  },
  {
    "id": 2,
    "name": "Burger Tuesday",
    "venue": "Zarillo",
    "description": "Burgers 1% off if you wash the dishes",
    "latitude": "61.496705",
    "longitude": "23.7708255",
    "busstops": ["1984", "2001", "2112"],
    "priority": 0
  }
]

userCoordinates = {
  "latitude": "61.497431",
  "longitude": "23.768822"
}
```
Printing without sorting:
```js
for (event of events) {
  console.log(event.name);
}
```
outputs
```
Bowling discount
Free buckets
Zarillo
```

Implement a sort function:
```js
function proximity(userCoordinates, events) {
  // do something
}
```
Printing the sorted events
```js
for (event of proximity(userCoordinates, events)) {
    console.log(event.name);
}
```
outputs
```
Zarillo
Free buckets
Bowling discount
```

**Comment by Mxdcq** [comment]
/**
- Created by mingxiaodong on 11/9/16.
  */

var events = [
    {
        "id": 0,
        "name": "Bowling discount",
        "venue": "",
        "description": "",
        "latitude": "61.494413",
        "longitude": "23.762998",
        "busstops": ["1337", "8888"],
        "priority": 0
    },
    {
        "id": 1,
        "name": "Free buckets",
        "venue": "Hämeensilta",
        "description": "Buy a Tesla, get one bucket for free",
        "latitude": "61.498002",
        "longitude": "23.763586",
        "busstops": ["4311", "0800", "8135"],
        "priority": 0
    },
    {
        "id": 2,
        "name": "Burger Tuesday",
        "venue": "Zarillo",
        "description": "Burgers 1% off if you wash the dishes",
        "latitude": "61.496705",
        "longitude": "23.7708255",
        "busstops": ["1984", "2001", "2112"],
        "priority": 0
    },
    {
        "id": 3,
        "name": "Coffee tasting",
        "venue": "Pispalan Haulitehdas",
        "description": "We have Euroshopper and Rainbow coffee",
        "latitude": "61.505228",
        "longitude": "23.711523",
        "busstops": [],
        "priority": 0
    },
    {
        "id": 4,
        "name": "Maitreya is coming",
        "venue": "",
        "description": "real soon now",
        "latitude": "61.499089",
        "longitude": "23.778980",
        "busstops": ["9001"],
        "priority": 0
    }
]

var userCoordinates = {
    "latitude": "61.497431",
    "longtitude": "23.768822"
}

function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
    var R = 6371; // Radius of the earth in km
    var dLat = deg2rad(lat2-lat1);  // deg2rad below
    var dLon = deg2rad(lon2-lon1);
    var a =
            Math.sin(dLat/2) \* Math.sin(dLat/2) +
            Math.cos(deg2rad(lat1)) \* Math.cos(deg2rad(lat2)) *
            Math.sin(dLon/2) \* Math.sin(dLon/2)
        ;
    var c = 2 \* Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R \* c; // Distance in km
    return d;
}

function deg2rad(deg) {
    return deg \* (Math.PI/180)
}

function proximity(userCoordinates, events) {
    var distance_list = [];
    for(var i = 0; i < events.length; i++) {
        distance_list.push(events[i].name + " " + getDistanceFromLatLonInKm(Number(events[i].latitude), Number(events[i].longitude), Number(userCoordinates.latitude), Number(userCoordinates.longtitude)));
    }
    return distance_list;
}

console.log(proximity(userCoordinates, events));

### output

[ 'Bowling discount 0.456211490099265',
  'Free buckets 0.2849927548913342',
  'Burger Tuesday 0.13348766954553154',
  'Coffee tasting 3.16123131415018',
  'Maitreya is coming 0.5696479782647504' ]

**Comment by antti-TIEA4** [comment]
That's a good start. Now that I look into Angular filters they are not what I though they were. They are just meant to format text. So let's forget about the filters. I guess we need to re-calculate the distances every time the user's location is updated (and has not changed) and then render the event list again.

The main idea is to list the events in the UI from top to bottom sorted by proximity to the user.

This doesn't have a high priority for now.

**Comment by antti-TIEA4** [comment]
Would be also cool if we could return some kind of iterables (instead of creating a new array) and use those to go through the original array in the correct order. Dunno how to do this in javascript.

**Comment by antti-TIEA4** [comment]
Oops... `ng-repeat` does have `orderBy` https://docs.angularjs.org/api/ng/filter/orderBy
